# Generated by Django 5.1.15 on 2026-03-27 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('isbn', models.CharField(help_text='Enter a 10 or 13 digit ISBN number.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be 10 or 13 digits.', regex='^\\d{10}(\\d{3})?$')], verbose_name='ISBN')),
                ('published_date', models.DateField(verbose_name='published date')),
                ('page_count', models.PositiveIntegerField(verbose_name='page count')),
                ('language', models.CharField(default='English', max_length=50, verbose_name='language')),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('science', 'Science'), ('technology', 'Technology'), ('history', 'History'), ('biography', 'Biography'), ('philosophy', 'Philosophy'), ('poetry', 'Poetry'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('self_help', 'Self-Help'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='genre')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['-created_at'],
            },
        ),
    ]
